openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/users/:
    get:
      operationId: listCustomUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomUser'
          description: ''
      tags:
      - api
    post:
      operationId: createCustomUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomUser'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
      tags:
      - api
  /api/users/{id}/:
    get:
      operationId: retrieveCustomUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this custom user.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
      tags:
      - api
    put:
      operationId: updateCustomUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this custom user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomUser'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCustomUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this custom user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomUser'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCustomUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this custom user.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/product/:
    get:
      operationId: listProducts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductCard'
          description: ''
      tags:
      - api
    post:
      operationId: createProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductCard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductCard'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCard'
          description: ''
      tags:
      - api
  /api/product/{id}/:
    get:
      operationId: retrieveProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCard'
          description: ''
      tags:
      - api
    put:
      operationId: updateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductCard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductCard'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCard'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductCard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductCard'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCard'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    CustomUser:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          maxLength: 128
      required:
      - password
    ProductCard:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\
            \u043E\u0434\u0443\u043A\u0442\u0430"
          maxLength: 100
        image:
          type: string
          format: binary
          description: "\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0438\
            \u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u0442\u043E\
            \u0432\u0430\u0440\u0430"
        description:
          type: string
          description: "\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435 \u043F\u0440\
            \u043E\u0434\u0443\u043A\u0442\u0430"
          maxLength: 500
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000
          minimum: -100000000
          description: "\u0426\u0435\u043D\u0430 \u043F\u0440\u043E\u0434\u0443\u043A\
            \u0442\u0430"
        sizes:
          enum:
          - S
          - M
          - L
          - XL
          type: string
          description: "\u0420\u0430\u0437\u043C\u0435\u0440\u044B \u043F\u0440\u043E\
            \u0434\u0443\u043A\u0442\u0430"
        colors:
          enum:
          - Gray
          - Black
          - White
          - Red
          type: string
          description: "\u0426\u0432\u0435\u0442\u0430 \u043F\u0440\u043E\u0434\u0443\
            \u043A\u0442\u0430"
        category:
          enum:
          - T-shirts
          - Trousers
          - Shorts
          - Hoodie
          type: string
          description: "\u041A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F \u043F\
            \u0440\u043E\u0434\u0443\u043A\u0442\u0430"
        review:
          type: array
          items:
            type: object
            properties:
              user:
                type: integer
                description: "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\
                  \u0435\u043B\u044C, \u043E\u0441\u0442\u0430\u0432\u0438\u0432\u0448\
                  \u0438\u0439 \u043E\u0442\u0437\u044B\u0432"
              text:
                type: string
                description: "\u0422\u0435\u043A\u0441\u0442 \u043E\u0442\u0437\u044B\
                  \u0432\u0430 \u043E \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0435"
              rating:
                type: integer
                maximum: 10
                minimum: 1
                description: "\u041E\u0446\u0435\u043D\u043A\u0430, \u043A\u043E\u0442\
                  \u043E\u0440\u0443\u044E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\
                  \u0430\u0442\u0435\u043B\u044C \u043F\u043E\u0441\u0442\u0430\u0432\
                  \u0438\u043B \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0443"
            required:
            - user
            - text
          readOnly: true
      required:
      - name
      - image
      - description
      - price
      - sizes
      - colors
      - category
