# Generated by Django 5.0.4 on 2024-05-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Количество данного продукта в корзине', verbose_name='Количество')),
                ('product', models.ForeignKey(help_text='Продукт, добавленный в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='product.product', verbose_name='Продукт')),
            ],
        ),
    ]
