# Generated by Django 5.0.4 on 2024-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Статус заказа (обрабатывается, доставляется, и т.д.)', max_length=100, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа', verbose_name='Дата создания заказа')),
                ('products', models.ManyToManyField(help_text='Список продуктов, входящих в заказ', related_name='orders', to='product.product', verbose_name='Продукты')),
            ],
        ),
    ]
