# Generated by Django 5.0.4 on 2024-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание продукта', max_length=500, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена продукта', max_digits=10, verbose_name='Цена')),
                ('sizes', models.CharField(help_text='Размеры продукта', max_length=50, verbose_name='Размеры')),
                ('colors', models.CharField(help_text='Цвета продукта', max_length=50, verbose_name='Цвета')),
                ('category', models.CharField(choices=[('T-shirts', 'Футболки'), ('Trousers', 'Брюки'), ('Shorts', 'Шорты'), ('Hoodie', 'Худи')], help_text='Категория продукта', max_length=50, verbose_name='Категория')),
            ],
        ),
    ]
