# Generated by Django 5.0.4 on 2024-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, help_text='Загрузите изображение товара', upload_to='images/', verbose_name='Изображенин товара'),
            preserve_default=False,
        ),
    ]
