# Generated by Django 5.0.4 on 2024-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_colors_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Текущая цена продукта', max_digits=10, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Старая цена продукта', max_digits=10, verbose_name='Старая цена'),
            preserve_default=False,
        ),
    ]
