# Generated by Django 5.0.4 on 2024-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_price_product_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Red', 'Красный')], help_text='Цвет продукта', max_length=10, unique=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S, EUR: 38, RUS 44'), ('M', 'M, EUR: 40, RUS 46'), ('L', 'L, EUR: 42, RUS 48'), ('XL', 'XL, EUR: 44, RUS 50')], help_text='Размер продукта', max_length=2, unique=True, verbose_name='Размер')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(help_text='Цвета продукта', to='product.color', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Размеры продукта', to='product.size', verbose_name='Размеры'),
        ),
    ]
