# Generated by Django 5.0.4 on 2024-06-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_color_size_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('Серый', 'Серый'), ('Чёрный', 'Чёрный'), ('Белый', 'Белый'), ('Красный', 'Красный')], help_text='Цвет продукта', max_length=10, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S, EUR: 38, RUS 44', 'S, EUR: 38, RUS 44'), ('M, EUR: 40, RUS 46', 'M, EUR: 40, RUS 46'), ('L, EUR: 42, RUS 48', 'L, EUR: 42, RUS 48'), ('XL, EUR: 44, RUS 50', 'XL, EUR: 44, RUS 50')], help_text='Размер продукта', max_length=20, unique=True, verbose_name='Размер'),
        ),
    ]
