# Generated by Django 5.0.4 on 2024-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_color_color_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('Серый', 'Серый'), ('Чёрный', 'Чёрный'), ('Белый', 'Белый'), ('Красный', 'Красный')], help_text='Цвет продукта', max_length=20, unique=True, verbose_name='Цвет'),
        ),
    ]
