# Generated by Django 5.0.4 on 2024-05-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст отзыва о продукте', verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(help_text='Оценка, которую пользователь поставил продукту', verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания отзыва')),
                ('product', models.ForeignKey(help_text='Продукт, к которому относится отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='Продукт')),
            ],
        ),
    ]
